name: Create Release Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Tag the rel
      id: tag
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        TAG_NAME="rel-${TIMESTAMP}"
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

    - name: Create tag
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git tag ${{ env.TAG_NAME }}
        git push origin ${{ env.TAG_NAME }}

